#The blocks that can be replaced with a grave
#If it starts with '#' it is a tag
replaceable_blocks = ["minecraft:tall_grass", "minecraft:grass", "minecraft:water", "minecraft:lava", "minecraft:dandelion", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:sunflower", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:azure_bluet", "minecraft:oxeye_daisy", "minecraft:orange_tulip", "minecraft:pink_tulip", "minecraft:red_tulip", "minecraft:white_tulip", "minecraft:allium", "minecraft:fern", "minecraft:large_fern", "minecraft:spruce_sapling", "minecraft:acacia_sapling", "minecraft:birch_sapling", "minecraft:dark_oak_sapling", "minecraft:jungle_sapling", "minecraft:oak_sapling", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:snow", "minecraft:vine", "minecraft:dead_bush", "minecraft:fire"]
#If this is set to true only the player that owns the grave and admins can break the grave
only_owners_can_break = true
#If this is set to true the ghost of the dead player will be spawned when the grave is broken
spawn_ghost = false
#If this is set to true the ghost player will defend the player
friendly_ghost = true
#If this is set to true you get an obituary after you died
enable_obituary = true
#If this is set to true the obituary will be taken out of your inventory when you break the grave
remove_obituary = true
#If this is set to true you get your items back into your inventory by sneaking on the grave
sneak_pickup = true
#If this is set to true you get your items sorted back into your inventory by breaking the grave
break_pickup = true

