
#'Variant16x' Common Configuration File | Game Version: 1.16.5
[variant16x]

	#General Settings
	#NOTE: Changing 'General Settings' WILL OVERRIDE Custom Settings!
	[variant16x.general]
		#Enables/Disables ALL Pressure Plate Variants
		enablePressurePlates = true
		#Enables/Disables ALL Button Variants
		enableButtons = true
		#Enables/Disables ALL Miscellaneous Variants
		enableMiscellaneous = true
		#Enables/Disables ALL Stairs Variants
		enableStairs = true
		#Enables/Disables ALL Wall Variants
		enableWalls = true
		#Enables/Disables ALL Fence Gate Variants
		enableFenceGates = true
		#Enables/Disables ALL Fence Variants
		enableFences = true
		#Enables/Disables ALL Slab Variants
		enableSlabs = true

	#Custom Wall Settings
	[variant16x.walls]
		#Enables/Disables Stone Wall Variants
		enableStoneWalls = true
		#Enables/Disables Wool Wall Variants
		enableWoolWalls = true
		#Enables/Disables End Stone Wall
		enableEndStoneWalls = true
		#Enables/Disables Terracotta Wall Variants
		enableTerracottaWalls = true
		#Enables/Disables Prismarine Wall Variants
		enablePrismarineWalls = true
		#Enables/Disables Honeycomb Wall
		enableHoneycombWalls = true
		#Enables/Disables Obsidian Wall Variants
		enableObsidianWalls = true
		#Enables/Disables Glass Wall Variants
		enableGlassWalls = true
		#Enables/Disables Sandstone Wall Variants
		enableSandstoneWalls = true
		#Enables/Disables Cracked Nether Brick Wall
		enableNetherBrickWalls = true
		#Enables/Disables Purpur Wall
		enablePurpurWalls = true
		#Enables/Disables Concrete Wall Variants
		enableConcreteWalls = true
		#Enables/Disables Quartz Wall Variants
		enableQuartzWalls = true

	#Custom Fence Settings
	[variant16x.fences]
		#Enables/Disables Wood/Hyphae Fence Variants
		enableWoodFences = true
		#Enables/Disables Red Nether Brick Fence
		enableNetherBrickFences = true

	#Custom Button Settings
	[variant16x.buttons]
		#Enables/Disables Stone Button Variants
		enableStoneButtons = true
		#Enables/Disables Terracotta Button Variants
		enableTerracottaButtons = true
		#Enables/Disables Sandstone Button Variants
		enableSandstoneButtons = true
		#Enables/Disables Concrete Button Variants
		enableConcreteButtons = true
		#Enables/Disables Prismarine Button Variants
		enablePrismarineButtons = true
		#Enables/Disables Brick Button
		enableBrickButtons = true
		#Enables/Disables Glass Button Variants
		enableGlassButtons = true
		#Enables/Disables Purpur Button
		enablePurpurButtons = true
		#Enables/Disables Obsidian Button Variants
		enableObsidianButtons = true
		#Enables/Disables Wood/Hyphae Button Variants
		enableWoodButtons = true
		#Enables/Disables Quartz Button Variants
		enableQuartzButtons = true
		#Enables/Disables Wool Button Variants
		enableWoolButtons = false
		#Enables/Disables Honeycomb Button
		enableHoneycombButtons = true
		#Enables/Disables Nether Brick Button Variants
		enableNetherBrickButtons = true
		#Enables/Disables End Stone Button Variants
		enableEndStoneButtons = true

	#Custom Miscellaneous Settings
	[variant16x.miscellaneous]
		#Enables/Disables Infested Stone Variants
		enableInfestedStones = true
		#Enables/Disables Music Disc: C418 - dog
		enableMusicDiscs = true
		#Enables/Disables Boat Variants
		enableBoats = true
		#Enables/Disables Flower Variants
		enableSmallFlowers = true
		#Enables/Disables Weighted Pressure Plate Variants
		enableWeightedPressurePlates = true

	#Custom Pressure Plate Settings
	[variant16x.pressurePlates]
		#Enables/Disables Wood/Hyphae Pressure Plate Variants
		enableWoodPressurePlates = true
		#Enables/Disables Brick Pressure Plate
		enableBrickPressurePlates = true
		#Enables/Disables Purpur Pressure Plate
		enablePurpurPressurePlates = true
		#Enables/Disables Honeycomb Pressure Plate
		enableHoneycombPressurePlates = true
		#Enables/Disables Glass Pressure Plate Variants
		enableGlassPressurePlates = true
		#Enables/Disables Wool Pressure Plate Variants
		enableWoolPressurePlates = true
		#Enables/Disables Nether Brick Pressure Plate Variants
		enableNetherBrickPressurePlates = true
		#Enables/Disables Concrete Pressure Plate Variants
		enableConcretePressurePlates = true
		#Enables/Disables Prismarine Pressure Plate Variants
		enablePrismarinePressurePlates = true
		#Enables/Disables Stone Pressure Plate Variants
		enableStonePressurePlates = true
		#Enables/Disables Sandstone Pressure Plate Variants
		enableSandstonePressurePlates = true
		#Enables/Disables Obsidian Pressure Plate Variants
		enableObsidianPressurePlates = true
		#Enables/Disables End Stone Pressure Plate Variants
		enableEndStonePressurePlates = true
		#Enables/Disables Quartz Pressure Plate Variants
		enableQuartzPressurePlates = true
		#Enables/Disables Terracotta Pressure Plate Variants
		enableTerracottaPressurePlates = true

	#Custom Stairs Settings
	[variant16x.stairs]
		#Enables/Disables Wood/Hyphae Stairs Variants
		enableWoodStairs = true
		#Enables/Disables Glass Stairs Variants
		enableGlassStairs = true
		#Enables/Disables End Stone Stairs
		enableEndStoneStairs = true
		#Enables/Disables Quartz Brick Stairs
		enableQuartzStairs = true
		#Enables/Disables Terracotta Stairs Variants
		enableTerracottaStairs = true
		#Enables/Disables Stone Stairs Variants
		enableStoneStairs = true
		#Enables/Disables Obsidian Stairs Variants
		enableObsidianStairs = true
		#Enables/Disables Honeycomb Stairs
		enableHoneycombStairs = true
		#Enables/Disables Wool Stairs Variants
		enableWoolStairs = true
		#Enables/Disables Concrete Stairs Variants
		enableConcreteStairs = true
		#Enables/Disables Cracked Nether Brick Stairs
		enableNetherBrickStairs = true
		#Enables/Disables Sandstone Stairs Variants
		enableSandstoneStairs = true

	#Custom Fence Gate Settings
	[variant16x.fenceGates]
		#Enables/Disables Wood/Hyphae Fence Gate Variants
		enableWoodFenceGates = true

	#Custom Slab Settings
	[variant16x.slabs]
		#Enables/Disables Wool Slab Variants
		enableWoolSlabs = true
		#Enables/Disables Wood/Hyphae Slab Variants
		enableWoodSlabs = true
		#Enables/Disables End Stone Slab
		enableEndStoneSlabs = true
		#Enables/Disables Terracotta Slab Variants
		enableTerracottaSlabs = true
		#Enables/Disables Stone Slab Variants
		enableStoneSlabs = true
		#Enables/Disables Cracked Nether Brick Slab
		enableNetherBrickSlabs = true
		#Enables/Disables Concrete Slab Variants
		enableConcreteSlabs = true
		#Enables/Disables Quartz Brick Slab
		enableQuartzSlabs = true
		#Enables/Disables Obsidian Slab Variants
		enableObsidianSlabs = true
		#Enables/Disables Honeycomb Slab
		enableHoneycombSlabs = true
		#Enables/Disables Glass Slab Variants
		enableGlassSlabs = true

