
#Client Settings
[Client_Settings]
	#BYG Main Menu Panorama.
	Panorama = false
	#BYG's Biome Fog Settings.
	#Applies to "Overworld" ONLY. Color no longer works.
	#Allowed Values: DENSEFOGCOLOR, DENSEFOG, FOGCOLOR, OFF
	BiomeFog = "OFF"

