#Noise added to map to make it look less plastic
#Range: 0.0 ~ 0.5
noise = 0.05000000074505806
#Enables minimap to show up in corner
#Allowed Values: DISABLED, BOTTOM_LEFT, LEFT, TOP_LEFT, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
minimap = "DISABLED"
#Scale of minimap
#Range: 0.25 ~ 4.0
minimap_scale = 0.25
#Minimap will not rotate
minimap_locked_north = false
#Show waypoints on minimap
minimap_waypoints = false
#Show entities on minimap
minimap_entities = false
#Show entity heads on minimap
minimap_entity_heads = false
#Show player heads on minimap
minimap_player_heads = false
#Entities in minimap will be larger
minimap_large_entities = false
#Show XYZ under minimap
minimap_xyz = false
#Show biome under minimap
minimap_biome = false
#Blurs minimap
minimap_blur = false
#Adds NWSE compass inside minimap
minimap_compass = false
#Shadow intensity
#Range: 0.0 ~ 0.3
shadows = 0.10000000149011612
#Chunk grid overlay in large map
chunk_grid = false
#Reduces color palette to 256 colors
reduced_color_palette = false
#Color intensity
#Range: 0.0 ~ 1.0
saturation = 1.0
#Show claimed chunks on the map
claimed_chunks_on_map = true
#Show your own claimed chunks on the map
own_claimed_chunks_on_map = true
#Minimap visibility
#Range: 0 ~ 255
minimap_visibility = 255
#Show zone (claimed chunk or wilderness) under minimap
minimap_zone = true
#Enables debug info
debug_info = false
#Show waypoints in world
in_world_waypoints = false
#Different ways to render map
#Allowed Values: NONE, NIGHT, TOPOGRAPHY, BLOCKS, BIOME_TEMPERATURE, LIGHT_SOURCES
map_mode = "NONE"
#How many blocks should height checks skip in water. 0 means flat water, ignoring terrain
#Range: 0 ~ 128
water_height_factor = 8
#Enables creation of death waypoints
death_waypoints = true

