
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 63
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "RIGHT"
	#Toggle on by default
	byDefault = false
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 168
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "BOTTOM"
	#Inventory HUD mini mode
	invMini = true

#Settings for ArmorStatus HUD
[armorhud]
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 9
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 75
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "LEFT"
	#Show item durability bar
	armBars = false
	#Armor HUD type (ARMOR, FULL, FULL and empty inventory slots)
	#Allowed Values: ARMOR, FULL, FULL_AND_INV
	armType = "FULL_AND_INV"
	#Is Armor Damage HUD enabled
	ArmorDamage = false
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT
	armView = "PERCENTAGE"
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = 0
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 29
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "CENTER"
	#Potion HUD mini mode
	potMini = true
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 50
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 75
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "RIGHT"

