
["Mystical Agradditions"]
	#Set how many augments can be placed on the insanium tools
	#Range: 1 ~ 2
	insanium_tools_augments = 2
	#Set whether Insanium Armor can be enchanted using a enchantment table
	enchantable_insanium_armor = false
	#Set how many augments can be placed on the insanium armor
	#Range: 1 ~ 2
	insanium_armor_augments = 2
	#Set whether Insanium Tools can be enchanted using a enchantment table
	enchantable_insanium_tools = false

["Vampirism Compat"]
	#Enable the Daywalker Augment
	daywalker_augment = true
	#Enable the Thirstless Augment
	thirstless_augment = true

