#The amount of time to wait before cycling the displayed tip. This is in miliseconds. 1000ms = 1s
cycleTime = 11000
#A list of tip IDs to remove from the list. Restart is required for changes to take effect.
removedTips = ["tips:arthropods", "tips:boat_passenger", "tips:crouch_blocks", "tips:deflect_ghast_fireballs", "tips:dog_health", "tips:dog_rotten_flesh", "tips:iron_golem_heal", "tips:lava_fuel", "tips:lure_animals", "tips:nether_sponge", "tips:note_block_instrument", "tips:piglin_gold", "tips:poison_immune", "tips:scrap_nuggets", "tips:shulker_armor", "tips:shulker_golem", "tips:smoke_bees", "tips:undead_damage", "tips:undead_helmet", "tips:witch_conversion", "tips:wooden_tool_fuel", "tips:zombie_armor"]
#A list of tip namespaces to remove from the list. Restart is requird for changes to take effect.
removedNamespaces = []

